project:
  type: website
  output-dir: docs

website:
  title: "Paper on sentiment analysis and topic modelling"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: assignment2.qmd
        text: Main assignment
      - href: ref.bib
        text: references
      - href: https://github.com/sihlenjn 
        text: Github
echo: false
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
